# fly.toml app configuration file generated for openclaw-as0zdw on 2026-02-20T02:56:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openclaw-as0zdw'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 18789
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[processes]
  app = "node dist/index.js gateway --allow-unconfigured --port 18789 --bind lan"
  
[mounts]
  source = "openclaw_data"
  destination = "/root/.openclaw"
  
[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
